### ISSUE TITLE
Uncaught SyntaxError: missing ) after argument list

### ISSUE THREAD

**Issue by justinh00k** [mattiaz9/gatsby-plugin-runtime-path-prefix#7]
After force installing Gatsby v4, I get this error: 

Uncaught SyntaxError: missing ) after argument list

From what I gather on other relative path plugins, this may be a v4 issue.

**Comment by mattiaz9** [comment]
@justinh00k  I update the plugin. I'm not getting that error, but I wasn't getting it before, so I'm not sure if this will fix it.

**Comment by justinh00k** [comment]
Thanks for updating. Unfortunately I'm still getting that same error in the browser when I build with "gatsby build --prefix-paths"

**Comment by parajbs** [comment]
Hello **mattiaz9 and justinh00k,**

I've done several tests.
eg: with "https://github.com/gatsbyjs/gatsby-starter-hello-world"

**1st test:**
I have tested "gatsby-plugin-runtime-path-prefix" with different projects (with gatsby4), and I always get the same error, just at different places in the code of "app-*********. js"
`Error: Uncaught SyntaxError: missing ) after argument list`

At the point in the code of "app-*********.js":
`.catch((function(){throw new Error("We couldn't load \ __PATH_PREFIX__ + "/page-data/sq/d/"+t+'.json"')}))}))).then(`


**2nd test:**
I installed both "gatsby-plugin-runtime-path-prefix" and "gatsby-starter-hello-world" for gatsby3.14 and tested it afterwards and the gatsby3.14 version has the same error with the same error in code:
`Error: Uncaught SyntaxError: missing ) after argument list`

At the point in the code of "app-*********.js":
`.catch((function(){throw new Error("We couldn't load \ __PATH_PREFIX__ + "/page-data/sq/d/"+t+'.json"')}))}))).then(`

**3rd test:**
After that I put everything back to gatsby4 and manually corrected the error in the code of "app-*********.js" see below:

Correction in the code of "app-*********.js":
`.catch((function(){throw new Error("We couldn't load " + __PATH_PREFIX__ + "/page-data/sq/d/"+t+'.json"')}))}))).then (`
Now it works without error.

**4th test:**
I repeated test3, I first wrote a script that runs the fix after creating the "public" folder and automatically fixes the error in the code of "app-*********.js". corrected with the "sed" command.

Here is the fix sed command:
`sed -i "s/load \\/load \" \+/g" app-*.js`

**I have described it in such detail, it will be much easier for you to find the error in the source code.**
Since I also tested "gatsby-plugin-runtime-path-prefix" version 2.0.0 with "gatsby3.14" and got the same error, I think that the error is not due to "gatsby4", and the same error comes with different projects.

I will do further test to find the error in the source code. but i need help from you as you know your code better.

What I've noticed before is that the error occurs in .catch() where a "__PATH_PREFIX__" is set.

**Comment by parajbs** [comment]
Hello **mattiaz9,**

I found the errors in the source code.
I searched all node_modules for "We couldn't load", and found it twice in the "gastby":

**1. node_modules/gatsby/cache-dir/loader.js**
Line 310:
  **`We couldn't load "${__PATH_PREFIX__}/page-data/sq/d/${staticQueryHash}.json"`**

**2. node_modules/gatsby/cache-dir/commonjs/loader.js**
Line 326:
**throw new Error(`We couldn't load "${__PATH_PREFIX__}/page-data/sq/d/${staticQueryHash}.json"`);**

It seems that gatsby also uses "__PATH_PREFIX__", maybe you can solve the problem if you use another prefix like: "__GATSBY-PLUGIN-RUNTIME-PATH-PREFIX__" or something else.

I think it's because of that. Can you check it out?

**Comment by parajbs** [comment]
Hello **mattiaz9,**

I fixed the error by inserting this code in line 89 of the "relativizeJsContentFiles" function in the "src/path-fixers.js" file:

before:
```
     contents = contents
       .replace(pattern1, ` ${prefix} `)
       .replace(pattern2, (matches, g1, g2, g3) => ` ${prefix} + ${g1}/${g2}${g3}`)

     contents = `if(typeof ${prefix} === 'undefined'){${prefix}=''}${contents}`
```


after correction:
```
     contents = contents
       .replace(pattern1, ` ${prefix} `)
       .replace(pattern2, (matches, g1, g2, g3) => ` ${prefix} + ${g1}/${g2}${g3}`)
     contents = contents.replace(/load \\ /g, 'load " + ')
     contents = `if(typeof ${prefix} === 'undefined'){${prefix}=''}${contents}`
```



I added this line:
`     contents = contents.replace(/load \\ /g, 'load " + ')`

**After changing everything is super ok, and no more error messages!**

mattiaz9, i hope you understand.

**Comment by mattiaz9** [comment]
thank you @parajbs! I'll fix it soon
